### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by sitilge** [hoprnet/hoprd-operator#64]
@ausias-armesto since you are the author/developer of the operator and you know the inner workings, please add all the documentation on how to use, configure, how it fits in the picture, etc. for:
- The HOPRD operator
- The `Hoprd` CRD

**Comment by ausias-armesto** [comment]
@sitilge , Please do not assign me any other issue, and also remind to open the issues for the Core-Team to the hopr-devops repository. Please follow the procedures already agreed.
The assignment of issues is done in the Planning meeting before starting the iteration.
